openapi: 3.0.0
info:
  title: Gamery js
  version: '0.1'
paths:
  "/api/client/login":
    post:
      description: Effettua il login
      tags:
        - Users

      responses:
        '200':
          description: Login effettuato con successo
  "/api/client/register/temporary":
    post:
      description: Registra un nuovo utente temporaneo
      tags:
        - Users

      responses:
        '200':
          description: Token di accesso e uuid assegnato
        '400':
          description: Errore riscontrato in fase di creazione
  "/api/client/register":
    post:
      description: Registra un nuovo utente
      tags:
        - Users

      responses:
        '200':
          description: Token di accesso e uuid assegnato
        '400':
          description: Errore riscontrato in fase di creazione
  "/api/client/check":
    post:
      description: Controllo che il token passato sia valido
      tags:
        - Users

      responses:
        '200':
          description: Token di accesso e uuid assegnato
        '403':
          description: Accesso non consentito
  "/api/client/logout":
    get:
      description: Effettua ol logout
      tags:
        - Users

      responses:
        '200':
          description: Risposta di base
        '400':
          description: Errore durante l'esecuzione dell'azione
        '403':
          description: Accesso non consentito
  "/api/client":
    get:
      description: Informazioni dell'utente
      tags:
        - Users

      responses:
        '200':
          description: Dati dell'utente
        '400':
          description: Errore durante l'esecuzione dell'azione
        '403':
          description: Accesso non consentito
  "/api/client/confirm":
    get:
      description: Conferma l'indirizzo email
      tags:
        - Users
      parameters:
        - name: token
          description: Token inviato per email
          in: query
          required: true
          type: string

      responses:
        '200':
          description: Risultato dell'operazione
        '400':
          description: Errore durante l'esecuzione dell'azione
        '403':
          description: Accesso non consentito. Token non valido
  "/api/client/change/password":
    get:
      description: Form per inviare la modifica della password
      tags:
        - Users
      parameters:
        - name: token
          description: Token inviato per email
          in: query
          required: true
          schema:
            type: string

      responses:
        '200':
          description: Pagina web
        '400':
          description: Errore durante l'esecuzione dell'azione
        '403':
          description: Accesso non consentito. Token non valido
    post:
      description: Resetta la password per l'utente
      tags:
        - Users
      parameters:
        - name: token
          description: Token inviato per email
          in: query
          required: true
          schema:
           type: string
        - name: password
          description: La nuova password
          in: formData
          required: true
          schema:
            type: string
        - name: passwordConfirm
          description: Il doppio inserimento della nuova password
          in: formData
          required: true
          schema:
           type: string

      responses:
        '200':
          description: Successo dell'azione
        '400':
          description: Errore durante l'esecuzione dell'azione
        '403':
          description: Accesso non consentito. Token non valido
    put:
      description: Richiede un reset della password. Il link viene inviato per email
      tags:
        - Users
      parameters:
        - name: email
          description: Email al quale inviare il reset della password
          in: formData
          required: true
          schema:
           type: string

      responses:
        '200':
          description: Successo dell'azione
        '400':
          description: Errore durante l'esecuzione dell'azione
        '403':
          description: Accesso non consentito. Token non valido
  "/api/country":
    get:
      description: Ottiene tutti gli stati con le bandiere supportati
      tags:
        - Country

      responses:
        '200':
          description: Lista degli stati
        '403':
          description: Accesso negato
    post:
      description: Aggiunge i country al DB. Disponibile solo in localhost
      tags:
        - Country

      responses:
        '200':
          description: Il risultato dell'operazione
        '400':
          description: L'errore riscontrato se trovato
        '403':
          description: Accesso negato
  "/api/country/client":
    get:
      description: Ottiene il country scelto dall'utente
      tags:
        - Country

      responses:
        '200':
          description: Il country selezionato dall'utente
        '400':
          description: Errore riscontrato nell'esecuzione
        '403':
          description: Accesso negato
    put:
      description: Aggiorna lo stato assegnato all'utente
      tags:
        - Country

      parameters:
        - name: id
          description: Id dello stato
          in: formData
          required: false
          type: string
        - name: code
          description: Codice dello stato
          in: formData
          required: false
          type: string
        - name: remove
          description: Rimuove la preferenza dello stato
          in: formData
          required: false
          type: boolean
      responses:
        '200':
          description: L'utente aggiornato
        '400':
          description: Errore riscontrato nell'esecuzione
        '403':
          description: Accesso negato
    delete:
      description: Rimuove il country selezionato dall'utente
      tags:
        - Country

      responses:
        '200':
          description: Il country selezionato dall'utente
        '400':
          description: Errore riscontrato nell'esecuzione
        '403':
          description: Accesso negato
  "/api/game/word/":
    post:
      description: Aggiunge le parole al DB (solo LOCALHOST)
      tags:
        - Word

      parameters:
        - name: words
          description: All words
          in: formData
          required: true
          type: object
      responses:
        '200':
          description: Tutto salvato correttamente
        '403':
          description: Accesso non consentito
  "/api/game/":
    get:
      description: Ottiene l'ultima partita creata
      tags:
        - Game

      responses:
        '200':
          description: L'istanza del gioco
        '400':
          description: Istanza non trovata
        '401':
          description: Token non passato
        '403':
          description: Sessione o token non validi
    post:
      description: Genera una nuova partita
      tags:
        - Game

      responses:
        '200':
          description: L'istanza del gioco
        '400':
          description: Ha già una partita attiva
        '401':
          description: Token non passato
        '403':
          description: Sessione o token non validi
  "/api/game/round":
    post:
      description: Genera un nuovo round per l'ultima partita generata dall'utente
      tags:
        - Game

      responses:
        '200':
          description: Lista dei round
        '400':
          description: Errore riscontrato in fase di creazione
        '401':
          description: Token non passato
        '403':
          description: Sessione o token non validi
    get:
      description: informazioni di un terminato round
      tags:
        - Game

      responses:
        '200':
          description: Lista dei round
        '400':
          description: Errore riscontrato in fase di creazione
        '401':
          description: Token non passato
        '403':
          description: Sessione o token non validi
    put:
      description: Controllo su parole inserite al termine del round
      tags:
        - Game

      parameters:
        - name: words
          description: Lista delle parole inserite dall'utente
          in: formData
          required: true
          type: array
          items:
            type: string
        - name: gameTime
          description: Tempo impiegato nel round in secondi
          in: formData
          required: true
          type: number
      responses:
        '200':
          description: Informazioni sulla partita in corso
        '400':
          description: Errore riscontrato in fase di update
        '401':
          description: Token non passato
        '403':
          description: Sessione o token non validi
  "/api/game/recent":
    put:
      description: Ottengo le ultime partite dell'utente
      tags:
        - Statistics

      parameters:
      responses:
        '200':
          description: Ultime partite dell'utente
        '400':
          description: Errore riscontrato in fase di update
        '401':
          description: Token non passato
        '403':
          description: Sessione o token non validi
  "/api/":
    get:
      description: End point di prova
      tags:
        - Default

      responses:
        '200':
          description: Risposta corretta
  "/api/leaderboard":
    get:
      description: Ottiene la classifica con i filtri applicati
      tags:
        - Leaderboard
      responses:
        '200':
          description: Classifica
        '400':
          description: Errore durante la generazione
        '403':
          description: Accesso non consentito
  "/api/leaderboard/type":
    get:
      description: Ottiene i tipi di leaderboard supportati dalle API
      tags:
        - Leaderboard

      responses:
        '200':
          description: I tipi di classifica
        '403':
          description: Accesso non consentito
components: {}
tags: []

